/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { GooglerpcStatus } from '../models';
// @ts-ignore
import { V1ListShowReply } from '../models';
// @ts-ignore
import { V1ListShowRequest } from '../models';
// @ts-ignore
import { V1PlaceShowOrderReply } from '../models';
// @ts-ignore
import { V1PlaceShowOrderRequest } from '../models';
// @ts-ignore
import { V1Show } from '../models';
/**
 * ShowAppServiceApi - axios parameter creator
 * @export
 */
export const ShowAppServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showAppServiceAppGetShow: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('showAppServiceAppGetShow', 'id', id)
            const localVarPath = `/v1/ticketing/app/show/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [pageOffset] 
         * @param {number} [pageSize] 
         * @param {string} [search] 
         * @param {Array<string>} [sort] 
         * @param {string} [fields] 
         * @param {string} [filterId$eq] 
         * @param {string} [filterId$neq] 
         * @param {string} [filterId$contains] 
         * @param {string} [filterId$startsWith] 
         * @param {string} [filterId$nstartsWith] 
         * @param {string} [filterId$endsWith] 
         * @param {string} [filterId$nendsWith] 
         * @param {Array<string>} [filterId$in] 
         * @param {Array<string>} [filterId$nin] 
         * @param {boolean} [filterId$null] 
         * @param {boolean} [filterId$nnull] 
         * @param {boolean} [filterId$empty] 
         * @param {boolean} [filterId$nempty] 
         * @param {string} [filterId$like] 
         * @param {string} [filterName$eq] 
         * @param {string} [filterName$neq] 
         * @param {string} [filterName$contains] 
         * @param {string} [filterName$startsWith] 
         * @param {string} [filterName$nstartsWith] 
         * @param {string} [filterName$endsWith] 
         * @param {string} [filterName$nendsWith] 
         * @param {Array<string>} [filterName$in] 
         * @param {Array<string>} [filterName$nin] 
         * @param {boolean} [filterName$null] 
         * @param {boolean} [filterName$nnull] 
         * @param {boolean} [filterName$empty] 
         * @param {boolean} [filterName$nempty] 
         * @param {string} [filterName$like] 
         * @param {boolean} [filterIsRecommend$eq] 
         * @param {boolean} [filterIsRecommend$neq] 
         * @param {boolean} [filterIsRecommend$null] 
         * @param {boolean} [filterIsRecommend$nnull] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showAppServiceAppListShow: async (pageOffset?: number, pageSize?: number, search?: string, sort?: Array<string>, fields?: string, filterId$eq?: string, filterId$neq?: string, filterId$contains?: string, filterId$startsWith?: string, filterId$nstartsWith?: string, filterId$endsWith?: string, filterId$nendsWith?: string, filterId$in?: Array<string>, filterId$nin?: Array<string>, filterId$null?: boolean, filterId$nnull?: boolean, filterId$empty?: boolean, filterId$nempty?: boolean, filterId$like?: string, filterName$eq?: string, filterName$neq?: string, filterName$contains?: string, filterName$startsWith?: string, filterName$nstartsWith?: string, filterName$endsWith?: string, filterName$nendsWith?: string, filterName$in?: Array<string>, filterName$nin?: Array<string>, filterName$null?: boolean, filterName$nnull?: boolean, filterName$empty?: boolean, filterName$nempty?: boolean, filterName$like?: string, filterIsRecommend$eq?: boolean, filterIsRecommend$neq?: boolean, filterIsRecommend$null?: boolean, filterIsRecommend$nnull?: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/ticketing/app/show`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (pageOffset !== undefined) {
                localVarQueryParameter['pageOffset'] = pageOffset;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }

            if (fields !== undefined) {
                localVarQueryParameter['fields'] = fields;
            }

            if (filterId$eq !== undefined) {
                localVarQueryParameter['filter.id.$eq'] = filterId$eq;
            }

            if (filterId$neq !== undefined) {
                localVarQueryParameter['filter.id.$neq'] = filterId$neq;
            }

            if (filterId$contains !== undefined) {
                localVarQueryParameter['filter.id.$contains'] = filterId$contains;
            }

            if (filterId$startsWith !== undefined) {
                localVarQueryParameter['filter.id.$starts_with'] = filterId$startsWith;
            }

            if (filterId$nstartsWith !== undefined) {
                localVarQueryParameter['filter.id.$nstarts_with'] = filterId$nstartsWith;
            }

            if (filterId$endsWith !== undefined) {
                localVarQueryParameter['filter.id.$ends_with'] = filterId$endsWith;
            }

            if (filterId$nendsWith !== undefined) {
                localVarQueryParameter['filter.id.$nends_with'] = filterId$nendsWith;
            }

            if (filterId$in) {
                localVarQueryParameter['filter.id.$in'] = filterId$in;
            }

            if (filterId$nin) {
                localVarQueryParameter['filter.id.$nin'] = filterId$nin;
            }

            if (filterId$null !== undefined) {
                localVarQueryParameter['filter.id.$null'] = filterId$null;
            }

            if (filterId$nnull !== undefined) {
                localVarQueryParameter['filter.id.$nnull'] = filterId$nnull;
            }

            if (filterId$empty !== undefined) {
                localVarQueryParameter['filter.id.$empty'] = filterId$empty;
            }

            if (filterId$nempty !== undefined) {
                localVarQueryParameter['filter.id.$nempty'] = filterId$nempty;
            }

            if (filterId$like !== undefined) {
                localVarQueryParameter['filter.id.$like'] = filterId$like;
            }

            if (filterName$eq !== undefined) {
                localVarQueryParameter['filter.name.$eq'] = filterName$eq;
            }

            if (filterName$neq !== undefined) {
                localVarQueryParameter['filter.name.$neq'] = filterName$neq;
            }

            if (filterName$contains !== undefined) {
                localVarQueryParameter['filter.name.$contains'] = filterName$contains;
            }

            if (filterName$startsWith !== undefined) {
                localVarQueryParameter['filter.name.$starts_with'] = filterName$startsWith;
            }

            if (filterName$nstartsWith !== undefined) {
                localVarQueryParameter['filter.name.$nstarts_with'] = filterName$nstartsWith;
            }

            if (filterName$endsWith !== undefined) {
                localVarQueryParameter['filter.name.$ends_with'] = filterName$endsWith;
            }

            if (filterName$nendsWith !== undefined) {
                localVarQueryParameter['filter.name.$nends_with'] = filterName$nendsWith;
            }

            if (filterName$in) {
                localVarQueryParameter['filter.name.$in'] = filterName$in;
            }

            if (filterName$nin) {
                localVarQueryParameter['filter.name.$nin'] = filterName$nin;
            }

            if (filterName$null !== undefined) {
                localVarQueryParameter['filter.name.$null'] = filterName$null;
            }

            if (filterName$nnull !== undefined) {
                localVarQueryParameter['filter.name.$nnull'] = filterName$nnull;
            }

            if (filterName$empty !== undefined) {
                localVarQueryParameter['filter.name.$empty'] = filterName$empty;
            }

            if (filterName$nempty !== undefined) {
                localVarQueryParameter['filter.name.$nempty'] = filterName$nempty;
            }

            if (filterName$like !== undefined) {
                localVarQueryParameter['filter.name.$like'] = filterName$like;
            }

            if (filterIsRecommend$eq !== undefined) {
                localVarQueryParameter['filter.isRecommend.$eq'] = filterIsRecommend$eq;
            }

            if (filterIsRecommend$neq !== undefined) {
                localVarQueryParameter['filter.isRecommend.$neq'] = filterIsRecommend$neq;
            }

            if (filterIsRecommend$null !== undefined) {
                localVarQueryParameter['filter.isRecommend.$null'] = filterIsRecommend$null;
            }

            if (filterIsRecommend$nnull !== undefined) {
                localVarQueryParameter['filter.isRecommend.$nnull'] = filterIsRecommend$nnull;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {V1ListShowRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showAppServiceAppListShow2: async (body: V1ListShowRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('showAppServiceAppListShow2', 'body', body)
            const localVarPath = `/v1/ticketing/app/show/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {V1PlaceShowOrderRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showAppServicePlaceShowOrder: async (body: V1PlaceShowOrderRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('showAppServicePlaceShowOrder', 'body', body)
            const localVarPath = `/v1/ticketing/app/show/order`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ShowAppServiceApi - functional programming interface
 * @export
 */
export const ShowAppServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ShowAppServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async showAppServiceAppGetShow(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1Show>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.showAppServiceAppGetShow(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} [pageOffset] 
         * @param {number} [pageSize] 
         * @param {string} [search] 
         * @param {Array<string>} [sort] 
         * @param {string} [fields] 
         * @param {string} [filterId$eq] 
         * @param {string} [filterId$neq] 
         * @param {string} [filterId$contains] 
         * @param {string} [filterId$startsWith] 
         * @param {string} [filterId$nstartsWith] 
         * @param {string} [filterId$endsWith] 
         * @param {string} [filterId$nendsWith] 
         * @param {Array<string>} [filterId$in] 
         * @param {Array<string>} [filterId$nin] 
         * @param {boolean} [filterId$null] 
         * @param {boolean} [filterId$nnull] 
         * @param {boolean} [filterId$empty] 
         * @param {boolean} [filterId$nempty] 
         * @param {string} [filterId$like] 
         * @param {string} [filterName$eq] 
         * @param {string} [filterName$neq] 
         * @param {string} [filterName$contains] 
         * @param {string} [filterName$startsWith] 
         * @param {string} [filterName$nstartsWith] 
         * @param {string} [filterName$endsWith] 
         * @param {string} [filterName$nendsWith] 
         * @param {Array<string>} [filterName$in] 
         * @param {Array<string>} [filterName$nin] 
         * @param {boolean} [filterName$null] 
         * @param {boolean} [filterName$nnull] 
         * @param {boolean} [filterName$empty] 
         * @param {boolean} [filterName$nempty] 
         * @param {string} [filterName$like] 
         * @param {boolean} [filterIsRecommend$eq] 
         * @param {boolean} [filterIsRecommend$neq] 
         * @param {boolean} [filterIsRecommend$null] 
         * @param {boolean} [filterIsRecommend$nnull] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async showAppServiceAppListShow(pageOffset?: number, pageSize?: number, search?: string, sort?: Array<string>, fields?: string, filterId$eq?: string, filterId$neq?: string, filterId$contains?: string, filterId$startsWith?: string, filterId$nstartsWith?: string, filterId$endsWith?: string, filterId$nendsWith?: string, filterId$in?: Array<string>, filterId$nin?: Array<string>, filterId$null?: boolean, filterId$nnull?: boolean, filterId$empty?: boolean, filterId$nempty?: boolean, filterId$like?: string, filterName$eq?: string, filterName$neq?: string, filterName$contains?: string, filterName$startsWith?: string, filterName$nstartsWith?: string, filterName$endsWith?: string, filterName$nendsWith?: string, filterName$in?: Array<string>, filterName$nin?: Array<string>, filterName$null?: boolean, filterName$nnull?: boolean, filterName$empty?: boolean, filterName$nempty?: boolean, filterName$like?: string, filterIsRecommend$eq?: boolean, filterIsRecommend$neq?: boolean, filterIsRecommend$null?: boolean, filterIsRecommend$nnull?: boolean, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1ListShowReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.showAppServiceAppListShow(pageOffset, pageSize, search, sort, fields, filterId$eq, filterId$neq, filterId$contains, filterId$startsWith, filterId$nstartsWith, filterId$endsWith, filterId$nendsWith, filterId$in, filterId$nin, filterId$null, filterId$nnull, filterId$empty, filterId$nempty, filterId$like, filterName$eq, filterName$neq, filterName$contains, filterName$startsWith, filterName$nstartsWith, filterName$endsWith, filterName$nendsWith, filterName$in, filterName$nin, filterName$null, filterName$nnull, filterName$empty, filterName$nempty, filterName$like, filterIsRecommend$eq, filterIsRecommend$neq, filterIsRecommend$null, filterIsRecommend$nnull, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {V1ListShowRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async showAppServiceAppListShow2(body: V1ListShowRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1ListShowReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.showAppServiceAppListShow2(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {V1PlaceShowOrderRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async showAppServicePlaceShowOrder(body: V1PlaceShowOrderRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1PlaceShowOrderReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.showAppServicePlaceShowOrder(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ShowAppServiceApi - factory interface
 * @export
 */
export const ShowAppServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ShowAppServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {ShowAppServiceApiShowAppServiceAppGetShowRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showAppServiceAppGetShow(requestParameters: ShowAppServiceApiShowAppServiceAppGetShowRequest, options?: AxiosRequestConfig): AxiosPromise<V1Show> {
            return localVarFp.showAppServiceAppGetShow(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ShowAppServiceApiShowAppServiceAppListShowRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showAppServiceAppListShow(requestParameters: ShowAppServiceApiShowAppServiceAppListShowRequest = {}, options?: AxiosRequestConfig): AxiosPromise<V1ListShowReply> {
            return localVarFp.showAppServiceAppListShow(requestParameters.pageOffset, requestParameters.pageSize, requestParameters.search, requestParameters.sort, requestParameters.fields, requestParameters.filterId$eq, requestParameters.filterId$neq, requestParameters.filterId$contains, requestParameters.filterId$startsWith, requestParameters.filterId$nstartsWith, requestParameters.filterId$endsWith, requestParameters.filterId$nendsWith, requestParameters.filterId$in, requestParameters.filterId$nin, requestParameters.filterId$null, requestParameters.filterId$nnull, requestParameters.filterId$empty, requestParameters.filterId$nempty, requestParameters.filterId$like, requestParameters.filterName$eq, requestParameters.filterName$neq, requestParameters.filterName$contains, requestParameters.filterName$startsWith, requestParameters.filterName$nstartsWith, requestParameters.filterName$endsWith, requestParameters.filterName$nendsWith, requestParameters.filterName$in, requestParameters.filterName$nin, requestParameters.filterName$null, requestParameters.filterName$nnull, requestParameters.filterName$empty, requestParameters.filterName$nempty, requestParameters.filterName$like, requestParameters.filterIsRecommend$eq, requestParameters.filterIsRecommend$neq, requestParameters.filterIsRecommend$null, requestParameters.filterIsRecommend$nnull, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ShowAppServiceApiShowAppServiceAppListShow2Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showAppServiceAppListShow2(requestParameters: ShowAppServiceApiShowAppServiceAppListShow2Request, options?: AxiosRequestConfig): AxiosPromise<V1ListShowReply> {
            return localVarFp.showAppServiceAppListShow2(requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ShowAppServiceApiShowAppServicePlaceShowOrderRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showAppServicePlaceShowOrder(requestParameters: ShowAppServiceApiShowAppServicePlaceShowOrderRequest, options?: AxiosRequestConfig): AxiosPromise<V1PlaceShowOrderReply> {
            return localVarFp.showAppServicePlaceShowOrder(requestParameters.body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for showAppServiceAppGetShow operation in ShowAppServiceApi.
 * @export
 * @interface ShowAppServiceApiShowAppServiceAppGetShowRequest
 */
export interface ShowAppServiceApiShowAppServiceAppGetShowRequest {
    /**
     * 
     * @type {string}
     * @memberof ShowAppServiceApiShowAppServiceAppGetShow
     */
    readonly id: string
}

/**
 * Request parameters for showAppServiceAppListShow operation in ShowAppServiceApi.
 * @export
 * @interface ShowAppServiceApiShowAppServiceAppListShowRequest
 */
export interface ShowAppServiceApiShowAppServiceAppListShowRequest {
    /**
     * 
     * @type {number}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly pageOffset?: number

    /**
     * 
     * @type {number}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly pageSize?: number

    /**
     * 
     * @type {string}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly search?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly sort?: Array<string>

    /**
     * 
     * @type {string}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly fields?: string

    /**
     * 
     * @type {string}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterId$eq?: string

    /**
     * 
     * @type {string}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterId$neq?: string

    /**
     * 
     * @type {string}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterId$contains?: string

    /**
     * 
     * @type {string}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterId$startsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterId$nstartsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterId$endsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterId$nendsWith?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterId$in?: Array<string>

    /**
     * 
     * @type {Array<string>}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterId$nin?: Array<string>

    /**
     * 
     * @type {boolean}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterId$null?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterId$nnull?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterId$empty?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterId$nempty?: boolean

    /**
     * 
     * @type {string}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterId$like?: string

    /**
     * 
     * @type {string}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterName$eq?: string

    /**
     * 
     * @type {string}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterName$neq?: string

    /**
     * 
     * @type {string}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterName$contains?: string

    /**
     * 
     * @type {string}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterName$startsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterName$nstartsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterName$endsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterName$nendsWith?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterName$in?: Array<string>

    /**
     * 
     * @type {Array<string>}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterName$nin?: Array<string>

    /**
     * 
     * @type {boolean}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterName$null?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterName$nnull?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterName$empty?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterName$nempty?: boolean

    /**
     * 
     * @type {string}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterName$like?: string

    /**
     * 
     * @type {boolean}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterIsRecommend$eq?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterIsRecommend$neq?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterIsRecommend$null?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow
     */
    readonly filterIsRecommend$nnull?: boolean
}

/**
 * Request parameters for showAppServiceAppListShow2 operation in ShowAppServiceApi.
 * @export
 * @interface ShowAppServiceApiShowAppServiceAppListShow2Request
 */
export interface ShowAppServiceApiShowAppServiceAppListShow2Request {
    /**
     * 
     * @type {V1ListShowRequest}
     * @memberof ShowAppServiceApiShowAppServiceAppListShow2
     */
    readonly body: V1ListShowRequest
}

/**
 * Request parameters for showAppServicePlaceShowOrder operation in ShowAppServiceApi.
 * @export
 * @interface ShowAppServiceApiShowAppServicePlaceShowOrderRequest
 */
export interface ShowAppServiceApiShowAppServicePlaceShowOrderRequest {
    /**
     * 
     * @type {V1PlaceShowOrderRequest}
     * @memberof ShowAppServiceApiShowAppServicePlaceShowOrder
     */
    readonly body: V1PlaceShowOrderRequest
}

/**
 * ShowAppServiceApi - object-oriented interface
 * @export
 * @class ShowAppServiceApi
 * @extends {BaseAPI}
 */
export class ShowAppServiceApi extends BaseAPI {
    /**
     * 
     * @param {ShowAppServiceApiShowAppServiceAppGetShowRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShowAppServiceApi
     */
    public showAppServiceAppGetShow(requestParameters: ShowAppServiceApiShowAppServiceAppGetShowRequest, options?: AxiosRequestConfig) {
        return ShowAppServiceApiFp(this.configuration).showAppServiceAppGetShow(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ShowAppServiceApiShowAppServiceAppListShowRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShowAppServiceApi
     */
    public showAppServiceAppListShow(requestParameters: ShowAppServiceApiShowAppServiceAppListShowRequest = {}, options?: AxiosRequestConfig) {
        return ShowAppServiceApiFp(this.configuration).showAppServiceAppListShow(requestParameters.pageOffset, requestParameters.pageSize, requestParameters.search, requestParameters.sort, requestParameters.fields, requestParameters.filterId$eq, requestParameters.filterId$neq, requestParameters.filterId$contains, requestParameters.filterId$startsWith, requestParameters.filterId$nstartsWith, requestParameters.filterId$endsWith, requestParameters.filterId$nendsWith, requestParameters.filterId$in, requestParameters.filterId$nin, requestParameters.filterId$null, requestParameters.filterId$nnull, requestParameters.filterId$empty, requestParameters.filterId$nempty, requestParameters.filterId$like, requestParameters.filterName$eq, requestParameters.filterName$neq, requestParameters.filterName$contains, requestParameters.filterName$startsWith, requestParameters.filterName$nstartsWith, requestParameters.filterName$endsWith, requestParameters.filterName$nendsWith, requestParameters.filterName$in, requestParameters.filterName$nin, requestParameters.filterName$null, requestParameters.filterName$nnull, requestParameters.filterName$empty, requestParameters.filterName$nempty, requestParameters.filterName$like, requestParameters.filterIsRecommend$eq, requestParameters.filterIsRecommend$neq, requestParameters.filterIsRecommend$null, requestParameters.filterIsRecommend$nnull, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ShowAppServiceApiShowAppServiceAppListShow2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShowAppServiceApi
     */
    public showAppServiceAppListShow2(requestParameters: ShowAppServiceApiShowAppServiceAppListShow2Request, options?: AxiosRequestConfig) {
        return ShowAppServiceApiFp(this.configuration).showAppServiceAppListShow2(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ShowAppServiceApiShowAppServicePlaceShowOrderRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShowAppServiceApi
     */
    public showAppServicePlaceShowOrder(requestParameters: ShowAppServiceApiShowAppServicePlaceShowOrderRequest, options?: AxiosRequestConfig) {
        return ShowAppServiceApiFp(this.configuration).showAppServicePlaceShowOrder(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }
}
