/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { GooglerpcStatus } from '../models';
// @ts-ignore
import { V1PlaceShowOrderReply } from '../models';
// @ts-ignore
import { V1PlaceShowOrderRequest } from '../models';
/**
 * ShowAppServiceApi - axios parameter creator
 * @export
 */
export const ShowAppServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {V1PlaceShowOrderRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showAppServicePlaceShowOrder: async (body: V1PlaceShowOrderRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('showAppServicePlaceShowOrder', 'body', body)
            const localVarPath = `/v1/ticketing/app/show/order`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ShowAppServiceApi - functional programming interface
 * @export
 */
export const ShowAppServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ShowAppServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {V1PlaceShowOrderRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async showAppServicePlaceShowOrder(body: V1PlaceShowOrderRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1PlaceShowOrderReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.showAppServicePlaceShowOrder(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ShowAppServiceApi - factory interface
 * @export
 */
export const ShowAppServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ShowAppServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {ShowAppServiceApiShowAppServicePlaceShowOrderRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showAppServicePlaceShowOrder(requestParameters: ShowAppServiceApiShowAppServicePlaceShowOrderRequest, options?: AxiosRequestConfig): AxiosPromise<V1PlaceShowOrderReply> {
            return localVarFp.showAppServicePlaceShowOrder(requestParameters.body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for showAppServicePlaceShowOrder operation in ShowAppServiceApi.
 * @export
 * @interface ShowAppServiceApiShowAppServicePlaceShowOrderRequest
 */
export interface ShowAppServiceApiShowAppServicePlaceShowOrderRequest {
    /**
     * 
     * @type {V1PlaceShowOrderRequest}
     * @memberof ShowAppServiceApiShowAppServicePlaceShowOrder
     */
    readonly body: V1PlaceShowOrderRequest
}

/**
 * ShowAppServiceApi - object-oriented interface
 * @export
 * @class ShowAppServiceApi
 * @extends {BaseAPI}
 */
export class ShowAppServiceApi extends BaseAPI {
    /**
     * 
     * @param {ShowAppServiceApiShowAppServicePlaceShowOrderRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShowAppServiceApi
     */
    public showAppServicePlaceShowOrder(requestParameters: ShowAppServiceApiShowAppServicePlaceShowOrderRequest, options?: AxiosRequestConfig) {
        return ShowAppServiceApiFp(this.configuration).showAppServicePlaceShowOrder(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }
}
