/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { GooglerpcStatus } from '../models';
// @ts-ignore
import { V1ListAppBannerReply } from '../models';
/**
 * TicketingAppBannerServiceApi - axios parameter creator
 * @export
 */
export const TicketingAppBannerServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ticketingAppBannerServiceListAppBanner: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/ticketing/app/banner`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TicketingAppBannerServiceApi - functional programming interface
 * @export
 */
export const TicketingAppBannerServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TicketingAppBannerServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ticketingAppBannerServiceListAppBanner(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1ListAppBannerReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ticketingAppBannerServiceListAppBanner(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TicketingAppBannerServiceApi - factory interface
 * @export
 */
export const TicketingAppBannerServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TicketingAppBannerServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ticketingAppBannerServiceListAppBanner(options?: AxiosRequestConfig): AxiosPromise<V1ListAppBannerReply> {
            return localVarFp.ticketingAppBannerServiceListAppBanner(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TicketingAppBannerServiceApi - object-oriented interface
 * @export
 * @class TicketingAppBannerServiceApi
 * @extends {BaseAPI}
 */
export class TicketingAppBannerServiceApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TicketingAppBannerServiceApi
     */
    public ticketingAppBannerServiceListAppBanner(options?: AxiosRequestConfig) {
        return TicketingAppBannerServiceApiFp(this.configuration).ticketingAppBannerServiceListAppBanner(options).then((request) => request(this.axios, this.basePath));
    }
}
