/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { GooglerpcStatus } from '../models';
// @ts-ignore
import { V1ListAppCategoryReply } from '../models';
/**
 * TicketingCategoryAppServiceApi - axios parameter creator
 * @export
 */
export const TicketingCategoryAppServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ticketingCategoryAppServiceListAppCategory: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/ticketing/app/category`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ticketingCategoryAppServiceListAppCategory2: async (body: object, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('ticketingCategoryAppServiceListAppCategory2', 'body', body)
            const localVarPath = `/v1/ticketing/app/category/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TicketingCategoryAppServiceApi - functional programming interface
 * @export
 */
export const TicketingCategoryAppServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TicketingCategoryAppServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ticketingCategoryAppServiceListAppCategory(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1ListAppCategoryReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ticketingCategoryAppServiceListAppCategory(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ticketingCategoryAppServiceListAppCategory2(body: object, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1ListAppCategoryReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ticketingCategoryAppServiceListAppCategory2(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TicketingCategoryAppServiceApi - factory interface
 * @export
 */
export const TicketingCategoryAppServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TicketingCategoryAppServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ticketingCategoryAppServiceListAppCategory(options?: AxiosRequestConfig): AxiosPromise<V1ListAppCategoryReply> {
            return localVarFp.ticketingCategoryAppServiceListAppCategory(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TicketingCategoryAppServiceApiTicketingCategoryAppServiceListAppCategory2Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ticketingCategoryAppServiceListAppCategory2(requestParameters: TicketingCategoryAppServiceApiTicketingCategoryAppServiceListAppCategory2Request, options?: AxiosRequestConfig): AxiosPromise<V1ListAppCategoryReply> {
            return localVarFp.ticketingCategoryAppServiceListAppCategory2(requestParameters.body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for ticketingCategoryAppServiceListAppCategory2 operation in TicketingCategoryAppServiceApi.
 * @export
 * @interface TicketingCategoryAppServiceApiTicketingCategoryAppServiceListAppCategory2Request
 */
export interface TicketingCategoryAppServiceApiTicketingCategoryAppServiceListAppCategory2Request {
    /**
     * 
     * @type {object}
     * @memberof TicketingCategoryAppServiceApiTicketingCategoryAppServiceListAppCategory2
     */
    readonly body: object
}

/**
 * TicketingCategoryAppServiceApi - object-oriented interface
 * @export
 * @class TicketingCategoryAppServiceApi
 * @extends {BaseAPI}
 */
export class TicketingCategoryAppServiceApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TicketingCategoryAppServiceApi
     */
    public ticketingCategoryAppServiceListAppCategory(options?: AxiosRequestConfig) {
        return TicketingCategoryAppServiceApiFp(this.configuration).ticketingCategoryAppServiceListAppCategory(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TicketingCategoryAppServiceApiTicketingCategoryAppServiceListAppCategory2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TicketingCategoryAppServiceApi
     */
    public ticketingCategoryAppServiceListAppCategory2(requestParameters: TicketingCategoryAppServiceApiTicketingCategoryAppServiceListAppCategory2Request, options?: AxiosRequestConfig) {
        return TicketingCategoryAppServiceApiFp(this.configuration).ticketingCategoryAppServiceListAppCategory2(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }
}
