/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { V1TicketingMedia } from './v1-ticketing-media';

/**
 * 
 * @export
 * @interface ActivityServiceUpdateActivityRequestActivity
 */
export interface ActivityServiceUpdateActivityRequestActivity {
    /**
     * 
     * @type {string}
     * @memberof ActivityServiceUpdateActivityRequestActivity
     */
    'name'?: string;
    /**
     * 
     * @type {V1TicketingMedia}
     * @memberof ActivityServiceUpdateActivityRequestActivity
     */
    'mainPic'?: V1TicketingMedia;
    /**
     * 
     * @type {Array<V1TicketingMedia>}
     * @memberof ActivityServiceUpdateActivityRequestActivity
     */
    'medias'?: Array<V1TicketingMedia>;
    /**
     * 
     * @type {string}
     * @memberof ActivityServiceUpdateActivityRequestActivity
     */
    'desc'?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityServiceUpdateActivityRequestActivity
     */
    'shortDesc'?: string;
    /**
     * 
     * @type {object}
     * @memberof ActivityServiceUpdateActivityRequestActivity
     */
    'content'?: object;
    /**
     * 
     * @type {Array<string>}
     * @memberof ActivityServiceUpdateActivityRequestActivity
     */
    'categoryKeys'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ActivityServiceUpdateActivityRequestActivity
     */
    'seatSelectable'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ActivityServiceUpdateActivityRequestActivity
     */
    'duration'?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityServiceUpdateActivityRequestActivity
     */
    'notice'?: string;
}

