/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { LocationServiceUpdateLocationHallRequestHall } from './location-service-update-location-hall-request-hall';

/**
 * 
 * @export
 * @interface LocationServiceUpdateLocationHallRequest
 */
export interface LocationServiceUpdateLocationHallRequest {
    /**
     * 
     * @type {LocationServiceUpdateLocationHallRequestHall}
     * @memberof LocationServiceUpdateLocationHallRequest
     */
    'hall'?: LocationServiceUpdateLocationHallRequestHall;
}

