/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PriceInfoPb } from './price-info-pb';
// May contain unused imports in some cases
// @ts-ignore
import { V1SeatGroup } from './v1-seat-group';

/**
 * 
 * @export
 * @interface V1ActivityShowSalesType
 */
export interface V1ActivityShowSalesType {
    /**
     * 
     * @type {string}
     * @memberof V1ActivityShowSalesType
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ActivityShowSalesType
     */
    'name'?: string;
    /**
     * 
     * @type {V1SeatGroup}
     * @memberof V1ActivityShowSalesType
     */
    'seatGroup'?: V1SeatGroup;
    /**
     * 
     * @type {string}
     * @memberof V1ActivityShowSalesType
     */
    'seatGroupId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1ActivityShowSalesType
     */
    'saleableFrom'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ActivityShowSalesType
     */
    'saleableTo'?: string;
    /**
     * 
     * @type {PriceInfoPb}
     * @memberof V1ActivityShowSalesType
     */
    'price'?: PriceInfoPb;
}

