/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { LbsAddress } from './lbs-address';
// May contain unused imports in some cases
// @ts-ignore
import { V1ContactInfo } from './v1-contact-info';
// May contain unused imports in some cases
// @ts-ignore
import { V1TicketingMedia } from './v1-ticketing-media';

/**
 * 
 * @export
 * @interface V1CreateLocationRequest
 */
export interface V1CreateLocationRequest {
    /**
     * 
     * @type {string}
     * @memberof V1CreateLocationRequest
     */
    'name': string;
    /**
     * 
     * @type {V1TicketingMedia}
     * @memberof V1CreateLocationRequest
     */
    'logo'?: V1TicketingMedia;
    /**
     * 
     * @type {Array<V1TicketingMedia>}
     * @memberof V1CreateLocationRequest
     */
    'medias'?: Array<V1TicketingMedia>;
    /**
     * 
     * @type {string}
     * @memberof V1CreateLocationRequest
     */
    'desc'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateLocationRequest
     */
    'shortDesc'?: string;
    /**
     * 
     * @type {object}
     * @memberof V1CreateLocationRequest
     */
    'content'?: object;
    /**
     * 
     * @type {LbsAddress}
     * @memberof V1CreateLocationRequest
     */
    'address'?: LbsAddress;
    /**
     * 
     * @type {Array<V1TicketingMedia>}
     * @memberof V1CreateLocationRequest
     */
    'legalDocs'?: Array<V1TicketingMedia>;
    /**
     * 
     * @type {V1ContactInfo}
     * @memberof V1CreateLocationRequest
     */
    'publicContact'?: V1ContactInfo;
}

