/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { V1TicketingMedia } from './v1-ticketing-media';

/**
 * 
 * @export
 * @interface V1CreateBannerRequest
 */
export interface V1CreateBannerRequest {
    /**
     * 
     * @type {string}
     * @memberof V1CreateBannerRequest
     */
    'refType': string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateBannerRequest
     */
    'refId': string;
    /**
     * 
     * @type {V1TicketingMedia}
     * @memberof V1CreateBannerRequest
     */
    'mainPic'?: V1TicketingMedia;
}

