/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { V1Banner } from './v1-banner';

/**
 * 
 * @export
 * @interface V1ListAppBannerReply
 */
export interface V1ListAppBannerReply {
    /**
     * 
     * @type {Array<V1Banner>}
     * @memberof V1ListAppBannerReply
     */
    'items'?: Array<V1Banner>;
}

