/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { V1BannerFilter } from './v1-banner-filter';

/**
 * 
 * @export
 * @interface V1ListBannerRequest
 */
export interface V1ListBannerRequest {
    /**
     * 
     * @type {number}
     * @memberof V1ListBannerRequest
     */
    'pageOffset'?: number;
    /**
     * 
     * @type {number}
     * @memberof V1ListBannerRequest
     */
    'pageSize'?: number;
    /**
     * 
     * @type {string}
     * @memberof V1ListBannerRequest
     */
    'search'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1ListBannerRequest
     */
    'sort'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof V1ListBannerRequest
     */
    'fields'?: string;
    /**
     * 
     * @type {V1BannerFilter}
     * @memberof V1ListBannerRequest
     */
    'filter'?: V1BannerFilter;
}

