/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { V1ActivityShow } from './v1-activity-show';

/**
 * 
 * @export
 * @interface V1ListAppActivityShowReply
 */
export interface V1ListAppActivityShowReply {
    /**
     * 
     * @type {Array<V1ActivityShow>}
     * @memberof V1ListAppActivityShowReply
     */
    'shows'?: Array<V1ActivityShow>;
}

