/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { V1OrderSalesType } from './v1-order-sales-type';

/**
 * 
 * @export
 * @interface V1PlaceShowOrderRequest
 */
export interface V1PlaceShowOrderRequest {
    /**
     * 
     * @type {string}
     * @memberof V1PlaceShowOrderRequest
     */
    'showId'?: string;
    /**
     * 
     * @type {Array<V1OrderSalesType>}
     * @memberof V1PlaceShowOrderRequest
     */
    'salesType'?: Array<V1OrderSalesType>;
}

